languageCode = "en-us"
title = "Bay Metal Polish"
baseurl = "https://baymetalpolish.com"
disableKinds = ["taxonomy", "taxonomyTerm"]
publishDir = "docs"
theme = "hugograyscale"

[params]
description = "A Bay Area metal polishing business."